# - Sistema A Farmácia VidaPlus

In [1]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_1 = _dntk.execute_sql(
  'CREATE TABLE lotes_estoque AS\nSELECT *\nFROM \'Tabela_lotes_estoque - PaÌgina1.csv\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_1

   Count
0     10

In [2]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_2 = _dntk.execute_sql(
  'CREATE TABLE promocoes_temporarias AS\nSELECT *\nFROM \'Tabela_promocoes_temporarias - PaÌgina1.csv\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_2

   Count
0      6

In [3]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_3 = _dntk.execute_sql(
  'CREATE TABLE fornecedores AS\nSELECT *\nFROM \'Tabela_fornecedores - PaÌgina1.csv\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_3

   Count
0      6

In [25]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_4 = _dntk.execute_sql(
  'CREATE TABLE medicamentos AS\nSELECT *\nFROM \'Tabela_medicamentos - PaÌgina1.csv\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_4

   Count
0     10

<hr>

In [5]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_4 = _dntk.execute_sql(
  '-- COLUNA 1 \n\nINSERT INTO medicamentos (\n    nome,\n    categoria,\n    preco,\n    fabricante\n)\nVALUES (\n    \'Dipirona Sódica 500mg\',\n    \'analgesicos\',\n    12.90,\n    \'LabVida\'\n);',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_4

   Count
0      1

In [6]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_3 = _dntk.execute_sql(
  '-- COLUNA 2\n\nDELETE FROM fornecedores\nWHERE id = 17;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_3

   Count
0      1

In [7]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_1 = _dntk.execute_sql(
  '-- COLUNA 3\n\nALTER TABLE lotes_estoque\nADD COLUMN data_validade DATE;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_1

Empty DataFrame
Columns: [Success]
Index: []

In [8]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_4 = _dntk.execute_sql(
  '-- COLUNA 4\n\nUPDATE medicamentos\nSET preco = preco * 1.05\nWHERE categoria = \'genericos\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_4

   Count
0      5

In [9]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_1 = _dntk.execute_sql(
  '-- COLUNA 5 \nUPDATE lotes_estoque\nSET status = \'vencido\'\nWHERE status = \'ativo\'\n  AND data_validade < CURRENT_DATE;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_1

   Count
0      0

In [10]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_5 = _dntk.execute_sql(
  '-- COLUNA 6\n\n-- DELETE remove os registros, mas mantém a tabela.\n\nDELETE FROM promocoes_temporarias;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_5

   Count
0      6

In [11]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_6 = _dntk.execute_sql(
  '-- COLUNA 7\n\n-- No exercício 6 apenas os dados foram removidos.\n-- Agora a tabela não será mais utilizada.\n-- Por isso removemos a tabela completamente.\n\nDROP TABLE promocoes_temporarias;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_6

Empty DataFrame
Columns: [Success]
Index: []

In [12]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_7 = _dntk.execute_sql(
  '-- COLUNA 8 \nCREATE TABLE medicamentos_v2 (\n    id INTEGER PRIMARY KEY,\n    nome VARCHAR NOT NULL,\n    categoria VARCHAR NOT NULL,\n    preco FLOAT NOT NULL,\n    fabricante VARCHAR NOT NULL,\n    principio_ativo VARCHAR NOT NULL\n);',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_7

Empty DataFrame
Columns: [Count]
Index: []

In [27]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_4 = _dntk.execute_sql(
  '-- COLUNA 8/2\n\nINSERT INTO medicamentos_v2 (\n    id,\n    nome,\n    categoria,\n    preco,\n    fabricante,\n    principio_ativo\n)\nSELECT\n    id,\n    nome,\n    categoria,\n    preco,\n    fabricante,\n    \'a definir\'\nFROM medicamentos;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_4

   Count
0     10

In [29]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_8 = _dntk.execute_sql(
  '-- COLUNA 8/3\n\nDROP TABLE medicamentos;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_8

Empty DataFrame
Columns: [Success]
Index: []

<hr>

#  StreamCast

In [39]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_10 = _dntk.execute_sql(
  'CREATE TABLE episodios AS\nSELECT *\nFROM \'Tabela_episodios - PaÌgina1.csv\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_10

   Count
0     11

In [41]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_11 = _dntk.execute_sql(
  'CREATE TABLE podcasts AS\nSELECT *\nFROM \'Tabela_podcasts - PaÌgina1.csv\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_11

   Count
0     12

In [43]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_12 = _dntk.execute_sql(
  'CREATE TABLE recomendacoes_temporarias AS\nSELECT *\nFROM \'Tabela_recomendacoes_temporarias - PaÌgina1.csv\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_12

   Count
0      6

In [75]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_13 = _dntk.execute_sql(
  'SELECT *\nFROM inscricoes\nLIMIT 5;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_13

   id  assinante_id  podcast_id data_inscricao     status data_cancelamento
0   1          1001           1     2023-06-12      ativa              NULL
1   3          1003           4     2022-11-30  cancelada        2023-01-20
2   4          1004           6     2024-05-22      ativa              NULL
3   6          1006           9     2024-12-01    pausada              NULL
4   7          1007           8     2022-04-18  cancelada        2022-12-30

In [47]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_14 = _dntk.execute_sql(
  'SELECT name\nFROM sqlite_master\nWHERE type=\'table\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_14

                        name
0                  episodios
1               fornecedores
2                 inscricoes
3              lotes_estoque
4            medicamentos_v2
5                   podcasts
6  recomendacoes_temporarias

In [49]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_15 = _dntk.execute_sql(
  '-- COLUNA 9\n\nINSERT INTO episodios (\n    podcast_id,\n    titulo,\n    data_lancamento,\n    status\n)\nVALUES\n(12, \'Sons da Mata ao Amanhecer\', \'2026-04-10\', \'publicado\'),\n(12, \'Encontro com os Ribeirinhos\', \'2026-04-17\', \'publicado\'),\n(12, \'A Lenda do Boto-Cor-de-Rosa\', \'2026-04-24\', \'rascunho\'),\n(12, \'O Silêncio da Floresta à Noite\', \'2026-05-01\', \'rascunho\');',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_15

   Count
0      4

In [51]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_10 = _dntk.execute_sql(
  '-- COLUNA 10\n\nUPDATE episodios\nSET titulo = \'Como começar na jardinagem\'\nWHERE id = 287;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_10

   Count
0      1

In [53]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_10 = _dntk.execute_sql(
  '-- COLUNA 11\n\nUPDATE episodios\nSET status = \'publicado\'\nWHERE status = \'rascunho\'\n  AND data_lancamento <= CURRENT_DATE;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_10

   Count
0      6

In [77]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_13 = _dntk.execute_sql(
  '-- COLUNA 12 \n\nDELETE FROM inscricoes\nWHERE status = \'cancelada\'\n  AND substr(data_cancelamento, 1, 7)\n      IN (\'2025-01\', \'2025-02\', \'2025-03\');',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_13

   Count
0      0

In [79]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_11 = _dntk.execute_sql(
  '-- COLUNA 13\n\nUPDATE podcasts\nSET faixa_audiencia =\nCASE\n    WHEN total_reproducoes < 1000 THEN \'nicho\'\n    WHEN total_reproducoes <= 49999 THEN \'medio\'\n    ELSE \'popular\'\nEND;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_11

   Count
0     12

In [89]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_13 = _dntk.execute_sql(
  '-- COLUNA 14\n\nSELECT COUNT(*) AS total_a_remover\nFROM inscricoes\nWHERE status = \'cancelada\'\n  AND CAST(data_cancelamento AS DATE)\n      < CURRENT_DATE - INTERVAL \'2 years\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_13

   total_a_remover
0                2

In [91]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_13 = _dntk.execute_sql(
  '-- COLUNA 14 / 2\n\nDELETE FROM inscricoes\nWHERE status = \'cancelada\'\n  AND CAST(data_cancelamento AS DATE)\n      < CURRENT_DATE - INTERVAL \'2 years\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_13

   Count
0      2

In [93]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_16 = _dntk.execute_sql(
  '-- COLUNA 15\n\n-- Remove apenas os registros e mantém a estrutura da tabela.\n\nDELETE FROM recomendacoes_temporarias;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_16

   Count
0      6

In [95]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_17 = _dntk.execute_sql(
  '-- COLUNA 15 / 2\n\n-- Remove definitivamente a tabela do banco.\n\nDROP TABLE recomendacoes_temporarias;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_17

Empty DataFrame
Columns: [Success]
Index: []

In [97]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_18 = _dntk.execute_sql(
  '-- COLUNA 16\n\n-- Inserção de novo podcast\n\nINSERT INTO podcasts (\n    titulo,\n    categoria,\n    total_reproducoes,\n    faixa_audiencia\n)\nVALUES (\n    \'Cidades Invisíveis\',\n    \'urbanismo\',\n    0,\n    NULL\n);',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_18

   Count
0      1

In [101]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_19 = _dntk.execute_sql(
  '-- COLUNA 16 / 2\n\n-- Atualização de episódios abandonados\n\nUPDATE episodios\nSET status = \'arquivado\'\nWHERE status = \'rascunho\'\n  AND CAST(data_lancamento AS DATE)\n      < CURRENT_DATE - INTERVAL \'6 months\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_19

   Count
0      0

In [103]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_20 = _dntk.execute_sql(
  '-- COLUNA 16 / 3\n\n-- Remoção de inscrições canceladas há mais de 3 anos\n\nDELETE FROM inscricoes\nWHERE status = \'cancelada\'\n  AND CAST(data_cancelamento AS DATE)\n      < CURRENT_DATE - INTERVAL \'3 years\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_20

   Count
0      0

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=83355405-d481-41c9-b2dd-542ec5f122d3' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>